"""add bio to users
Revision ID: 4628d3f2d56c
Revises: bef8b33f7cd7
Create Date: 2026-03-02 12:44:58.215687
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4628d3f2d56c'
down_revision = 'bef8b33f7cd7'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
