"""add task versions, drafts, reminders
Revision ID: 8ff773e035e0
Revises: 6dfbefc5f811
Create Date: 2026-03-08 13:13:34.367236
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8ff773e035e0'
down_revision = '6dfbefc5f811'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('tag_colors', sa.Text(), nullable=True),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_drafts_id'), 'task_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_task_drafts_task_id'), 'task_drafts', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_drafts_user_id'), 'task_drafts', ['user_id'], unique=False)
    op.create_table('task_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('tag_colors', sa.Text(), nullable=True),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_versions_id'), 'task_versions', ['id'], unique=False)
    op.create_index(op.f('ix_task_versions_task_id'), 'task_versions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_versions_user_id'), 'task_versions', ['user_id'], unique=False)
    op.add_column(
        'tasks',
        sa.Column('reminder_sent_day_before', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'tasks',
        sa.Column('reminder_sent_30min', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.execute("UPDATE tasks SET reminder_sent_day_before = FALSE WHERE reminder_sent_day_before IS NULL")
    op.execute("UPDATE tasks SET reminder_sent_30min = FALSE WHERE reminder_sent_30min IS NULL")
    op.alter_column('tasks', 'reminder_sent_day_before', server_default=None)
    op.alter_column('tasks', 'reminder_sent_30min', server_default=None)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_sent_30min')
    op.drop_column('tasks', 'reminder_sent_day_before')
    op.drop_index(op.f('ix_task_versions_user_id'), table_name='task_versions')
    op.drop_index(op.f('ix_task_versions_task_id'), table_name='task_versions')
    op.drop_index(op.f('ix_task_versions_id'), table_name='task_versions')
    op.drop_table('task_versions')
    op.drop_index(op.f('ix_task_drafts_user_id'), table_name='task_drafts')
    op.drop_index(op.f('ix_task_drafts_task_id'), table_name='task_drafts')
    op.drop_index(op.f('ix_task_drafts_id'), table_name='task_drafts')
    op.drop_table('task_drafts')
    # ### end Alembic commands ###
