"""add profile fields and update requests
Revision ID: cb371b355ed5
Revises: 8ff773e035e0
Create Date: 2026-03-08 17:33:50.664612
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cb371b355ed5'
down_revision = '8ff773e035e0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_update_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('new_email', sa.String(), nullable=True),
    sa.Column('new_password_hash', sa.String(), nullable=True),
    sa.Column('new_full_name', sa.String(), nullable=True),
    sa.Column('new_phone', sa.String(), nullable=True),
    sa.Column('new_photo_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_update_requests_id'), 'user_update_requests', ['id'], unique=False)
    op.create_index(op.f('ix_user_update_requests_user_id'), 'user_update_requests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_data')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_user_update_requests_user_id'), table_name='user_update_requests')
    op.drop_index(op.f('ix_user_update_requests_id'), table_name='user_update_requests')
    op.drop_table('user_update_requests')
    # ### end Alembic commands ###
